.\JsonToFolderStructure.ps1 -JsonString @"
 {
   "AKBON": [
     {
       "author": "PiyushKPV",
       "downloadCount": 0,
       "name": "GraddyLines(Blue)",
       "thumbUrl": "https://dl.dropboxusercontent.com/s/sid1eic48rbnopb/20201007_215050_resize_54.jpg?dl=0",
       "url": "https://dl.dropboxusercontent.com/s/vb4w3fdeglp7cgn/20201007_215050.jpg?dl=0",
       "viewCount": 0
     },
     {
       "author": "PiyushKPV",
       "downloadCount": 0,
       "name": "GraddyLines(Red)",
       "thumbUrl": "https://dl.dropboxusercontent.com/s/txj4h28igs8rvej/20201007_215036_resize_43.jpg?dl=0",
       "url": "https://dl.dropboxusercontent.com/s/l3eya8oiv8hm94i/20201007_215036.jpg?dl=0",
       "viewCount": 0
     },
     {
       "author": "PiyushKPV",
       "downloadCount": 0,
       "name": "GraddyLines(Purple)",
       "thumbUrl": "https://dl.dropboxusercontent.com/s/sbf7nijnv8w9066/20201007_215018_resize_0.jpg?dl=0",
       "url": "https://dl.dropboxusercontent.com/s/le0i1hkz5jqnxlh/20201007_215018.jpg?dl=0",
       "viewCount": 0
     }
   ],
   "Abstract": [],
   "Amoled": [],
   "Animals": [],
   "Anime": [],
   "Apricot": [],
   "Asus": [],
   "Bloom": [],
   "Cartoon": [],
   "ColorOS": [],
   "Creative": [],
   "DarkAmoled": [],
   "Flower": [],
   "Games": [],
   "Google": [],
   "HTC": [],
   "HiOS": [],
   "Horror": [],
   "Huawei": [],
   "HyperOS": [],
   "Japes": [],
   "Liaca": [],
   "Love": [],
   "MIUI": [],
   "MaterialYou": [],
   "Minimal": [],
   "MinimalIllustration": [],
   "MoSalah": [],
   "MostPopular": {},
   "Motorola": [],
   "Movies": [],
   "Music": [],
   "Nature": [],
   "NightLife": [],
   "OnePlus": [],
   "OneUI": [],
   "OxygenOS": [],
   "Pastel": [],
   "Pathways": [],
   "People": [],
   "Pixel": [],
   "Realme": [],
   "Samsung": [],
   "SciFi": [],
   "Series": [],
   "Sony": [],
   "Sports": [],
   "SunView": [],
   "SuperHeroes": [],
   "Suraj": [],
   "Vehicles": [],
   "Vivo": [],
   "Wallpapers": [],
   "XOS": [],
   "Xiaomi": [],
   "ZTE": [],
   "iOS": [],
   "rUI": []
 }
"@ -RootFolderName "WallpaperStructure" -Verbose